volumes:
  postgres-data:
     name: n8n-postgres-data

services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=n8n
      - POSTGRES_PASSWORD=15SCH9kKcaJwDKA
    networks:
      - n8n-net
  n8n:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces:cached
    command: sleep infinity
    environment:
      DB_POSTGRESDB_HOST: postgres
      DB_TYPE: postgresdb
      DB_POSTGRESDB_PASSWORD: 15SCH9kKcaJwDKA
      VIRTUAL_HOST: ai.reval.ir
      VIRTUAL_PORT: 5678
      LETSENCRYPT_HOST: ai.reval.ir
    depends_on:
      - postgres
    networks:
      - n8n-net

networks:
  n8n-net:
    external: true
    name: nginx-proxy

