volumes:
  postgres-data:
     name: n8n-postgres-data

services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=n8n
      - POSTGRES_PASSWORD=15SCH9kKcaJwDKA
    networks:
      - n8n-net
  n8n:
    build:
      context: .
      dockerfile: Dockerfile
    image: noora-n8n:0.0.1
    volumes:
      - ..:/workspaces:cached
    command: sleep infinity
    environment:
      DB_POSTGRESDB_HOST: postgres
      DB_TYPE: postgresdb
      DB_POSTGRESDB_PASSWORD: 15SCH9kKcaJwDKA
      VIRTUAL_HOST: ai.reval.ir
      VIRTUAL_PORT: 5678
      LETSENCRYPT_HOST: ai.reval.ir
      N8N_HOST: ai.reval.ir
      N8N_PORT: 5678
      N8N_PROTOCOL: https
      NODE_ENV: production
      WEBHOOK_URL: https://ai.reval.ir
      GENERIC_TIMEZONE: Europe/Berlin
    depends_on:
      - postgres
    networks:
      - n8n-net
    ports:
      - "5678:5678"

networks:
  n8n-net:
    external: true
    name: nginx-proxy

